import type { JSX } from 'react';
import { Lock } from 'lucide-react';
import { cn } from '@/lib/utils';

interface ConfidentialityFooterProps {
  className?: string;
}

/**
 * Centered confidentiality footer with lock icon and legal text.
 */
export function ConfidentialityFooter({
  className,
}: ConfidentialityFooterProps): JSX.Element {
  return (
    <div
      className={cn(
        'flex w-full items-center justify-center gap-2 pt-4',
        className
      )}
    >
      <Lock className="h-3 w-3 text-[#78716C]" />
      <span className="text-center text-[11px] text-[#78716C]">
        This report is confidential and intended for authorized healthcare
        providers only. Generated by Sphinx AI &middot; MindWell Healthcare
      </span>
    </div>
  );
}
