// AI-generated content disclaimers
export const disclaimers = {
  default:
    'This content was generated by AI and should be reviewed by a professional.',
  medical:
    'This is not medical advice. Please consult with a healthcare professional.',
  // Add more disclaimers as needed
};
